[package]
name = "taurus"
version = "0.1.0"
authors = ["m-cat <scatman@bu.edu>"]
description = "A WIP roguelike game being developed in Rust."
license = "MIT"
repository = "https://github.com/m-cat/taurus"
readme = "README.md"

[dependencies]
num-traits = "0.1.37"
num="0.1"
rand="0.3.0"
fraction="0.3.4"
tcod = "0.11"
