[package]
name = "taurus"
version = "0.1.0"
authors = ["m-cat <scatman@bu.edu>"]

[[bin]]
doc = false
name = "taurus"
path = "src/bin/taurus.rs"

[dependencies]
num-traits = "0.1.37"
num="0.1"
rand="0.3.0"
fraction="0.3.4"
tcod = "0.11"
