* Gothala's Handbook of Intelligent Creatures
** Introduction
** Humans
Humans are by far the most dominant presence on this continent. Considering the astonishing and at times surprising capabilities of some other creatures in this manual the success of humans can be considered somewhat of an anomaly. Indeed, much has been written on this topic already, many speculating that humans possess the required balance of personality enabling them to effectively organize large, stable societies. All in all, us humans are not very interesting to talk about, and we won't dwell on them here.

Avg. height:
Avg. weight: 
Temperament: varied
Strengths: varied
Weaknesses: 
** Vampires
The vampire is a true denizen of the night. No other creature can match them during this time. Their presence is the main reason humans have come to fear the dark, and to cower within their homes at night accompanied by at least one cross on the walls. Many of the rumors concerning vampires are, of course, myth or hyperbole - the notion, for instance, that one bitten by a vampire will turn into one themself. And while awfully fond of blood, vampires can survive just fine without it, although a deficiency in blood tends to weaken them over time, much like a deficiency of meat among humans. They are said to reproduce asexually, though what this means I have no idea. 

Vampires are remarkably agile and fast, and have perhaps the best reflexes of any intelligent creature. They also have animal-like raw strength which surpasses humans, though they are not as strong as some other creatures like werewolves.
** Werewolves
* Gothala's Handbook of Interesting Creatures
** Introduction
** Skeletons
As it turns out, bones don't need a brain to move. Skeletons have puzzled scientists for millenia, but the fact remains, they're out there, and they're not friendly. Many have speculated that black magic is at work, but it seems that many skeletons are entirely autonomous and beholden to no master. If there's one thing all skeletons have in common, it's their complete disdain for anything with skin.

